#! vim: set ft=yaml ts=2:
---

- name: assert some things
  assert:
    that:
      - ansible_os_family in ["RedHat","Debian"]

- when: java.type == 'jre'
  include_tasks: "{{ ansible_os_family }}.yml"
