#! vim: ft=yaml ts=2:
---

# We do not know if we are allowed to distribute oracles stuff
# so we pass the path to the rpm
#
- name: assert
  assert:
    that:
      - external_archive_file is defined
      - external_archive_file|regex_search('^j..-' + {{ java.version }})

- name: java tar.gz is installed
  when: external_archive_file.endswith('.tar.gz)
  unarchive:
    src: "{{ external_archive_file }}"
    dest: /usr/local
    creates: /usr/local/{{ external_archive_file[0:2]-{{ java.version }}

- name: java rpm is installed
  when: external_archive_file.endswith('.rpm')
  include_role:
    name: rpm
  vars:
    rpm: external_archive_file[0:2]-{{ java.version }}
    rpm_src: "{{ external_rpm_file }}"
    rpm_dest: /tmp/oracle_jre-{{ java.full_version_string }}.rpm
