#! vim: ft=yaml ts=2:
---

- name: get rpm name from .rpm
  delegate_to: localhost
  check_mode: false
  changed_when: false
  command: rpm -qp --qf '%{NAME}' files/{{ java.external_archive_file }}
  args:
    warn: false
  register: _java_rpm_name

- debug: var=_java_rpm_name
  tags:
    - never
    - debug

- assert:
    that:
      - _java_rpm_name.startswith('jdk') or _java_rpm_name.startswith('jre')

- name: java rpm is installed
  include_role:
    name: rpm
  vars:
    rpm: "{{ _java_rpm_name.stdout }}"
    rpm_src: "{{ java.external_archive_file }}"
    rpm_dest: /tmp/{{ java.external_archive_file }}

